name: Manual Scrape and CSV Update

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: write  # Allow write access to the contents of the repository

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls -R  # List all files in the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scrapers
        run: |
          python tazz-scraper.py  # Correct the script name
          python glovo-scrap.py   # Correct the script name

      - name: Commit and Push CSV Updates
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # Configure git to use the token for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CorcoVs/Restaurant-List.git
          
          git add *.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CSVs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
