name: Manual Scrape and CSV Update

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scrapers
        run: |
          python tazz_scraper.py
          python glovo_scrap.py

      - name: Commit and Push CSV Updates
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CSVs"
          git push
